### PR TITLE
Accounting vendor added.

### PR DESCRIPTION
**Pull request by mikemclaren**
- Adds upgrades to the game.
- Bookkeeping Retainer added as a possible upgrade! Shows in the
market how much $ has been sunk for a particular item.
- Adds accounting vendor, Percy! He's not the best, but he's the
_crooked_ best. Only includes one upgrade, currently, but more are
to come!

### CODE REVIEW

**Comment by mikemclaren** [comment]
I keep forgetting to set my origin to this repo, not my fork, hence the pull request from my fork!

**Comment by mikemclaren** [comment]
Don't merge this quite yet, I'm seeing an error on retainer purchase I need to work through.

**Comment by mikemclaren** [comment]
Fixed it, should be good for looking at now. I had made a circular reference when adding upgrades. :disappointed:

**Comment by snollygolly** [comment]
Super excited to try this out.  Thanks for it!  Are there any tests needed for it?

**Comment by mikemclaren** [comment]
There are! Making some tests for the vendor and upgrades now.

**Comment by snollygolly** [comment]
I bought laser pointers earlier in the game, but I sold all of them.  Before I bought more, it said I had spent $0 on them.  I bought 20, and the modal shows I paid more than they cost per unit.

screen shot 2016-03-12 at 9 47 08 pm

**Comment by mikemclaren** [comment]
Yeah, I need to make bookkeeping a little "smarter". Right now it doesn't track until you actually get the bookkeeping upgrade (which I think makes sense, though I need messaging to reflect that), and it's not particularly smart, especially if you don't sell all of something.

What I think I need to do is throw a "boughtAt" array onto an item's inventory object. Every time you "buy" that item, an object that contains the units and amount bought at is appended to it. Once you hit 0 and the item's gone from the inventory, that count would reset, which is perfect! I didn't intend this to be a "historical" price tracker, just more of a short-term turn-to-turn tool.

**Comment by mikemclaren** [comment]
Added some tests and bookkeeping should in general work a lot better now. :)

**Comment by snollygolly** [comment]
Looks great, thank you so much! :shipit:

**Pull request merged**
